spring.application.name=delta-api-postgres
# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-icy-union-aq80zxko.c-8.us-east-1.aws.neon.tech/deltadb?sslmode=require
spring.datasource.username=joao
spring.datasource.password=DeltaProject#2026_Joao66
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true